package ch.ahoegger.docbox.shared.category;

import java.math.BigDecimal;
import java.util.Date;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;
import org.eclipse.scout.rt.shared.data.form.properties.AbstractPropertyData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "ch.ahoegger.docbox.client.partner.CategoryForm", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class CategoryFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  /**
   * access method for property CategoryId.
   */
  public BigDecimal getCategoryId() {
    return getCategoryIdProperty().getValue();
  }

  /**
   * access method for property CategoryId.
   */
  public void setCategoryId(BigDecimal categoryId) {
    getCategoryIdProperty().setValue(categoryId);
  }

  public CategoryIdProperty getCategoryIdProperty() {
    return getPropertyByClass(CategoryIdProperty.class);
  }

  public Description getDescription() {
    return getFieldByClass(Description.class);
  }

  public EndDate getEndDate() {
    return getFieldByClass(EndDate.class);
  }

  public Name getName() {
    return getFieldByClass(Name.class);
  }

  public StartDate getStartDate() {
    return getFieldByClass(StartDate.class);
  }

  public static class CategoryIdProperty extends AbstractPropertyData<BigDecimal> {

    private static final long serialVersionUID = 1L;
  }

  public static class Description extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class EndDate extends AbstractValueFieldData<Date> {

    private static final long serialVersionUID = 1L;
  }

  public static class Name extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class StartDate extends AbstractValueFieldData<Date> {

    private static final long serialVersionUID = 1L;
  }
}
