package ch.ahoegger.docbox.shared.conversation;

import java.math.BigDecimal;
import java.util.Date;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;
import org.eclipse.scout.rt.shared.data.form.properties.AbstractPropertyData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "ch.ahoegger.docbox.client.conversation.ConversationForm", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class ConversationFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  /**
   * access method for property ConversationId.
   */
  public BigDecimal getConversationId() {
    return getConversationIdProperty().getValue();
  }

  /**
   * access method for property ConversationId.
   */
  public void setConversationId(BigDecimal conversationId) {
    getConversationIdProperty().setValue(conversationId);
  }

  public ConversationIdProperty getConversationIdProperty() {
    return getPropertyByClass(ConversationIdProperty.class);
  }

  public EndDate getEndDate() {
    return getFieldByClass(EndDate.class);
  }

  public Name getName() {
    return getFieldByClass(Name.class);
  }

  public Notes getNotes() {
    return getFieldByClass(Notes.class);
  }

  public StartDate getStartDate() {
    return getFieldByClass(StartDate.class);
  }

  public static class ConversationIdProperty extends AbstractPropertyData<BigDecimal> {

    private static final long serialVersionUID = 1L;
  }

  public static class EndDate extends AbstractValueFieldData<Date> {

    private static final long serialVersionUID = 1L;
  }

  public static class Name extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class Notes extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class StartDate extends AbstractValueFieldData<Date> {

    private static final long serialVersionUID = 1L;
  }
}
