package ch.ahoegger.docbox.shared.administration;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.basic.table.AbstractTableRowData;
import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;
import org.eclipse.scout.rt.shared.data.form.fields.tablefield.AbstractTableFieldBeanData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "ch.ahoegger.docbox.client.administration.DbDumpForm", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class DbDumpFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  public DBScript getDBScript() {
    return getFieldByClass(DBScript.class);
  }

  public ErrorTable getErrorTable() {
    return getFieldByClass(ErrorTable.class);
  }

  public static class DBScript extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class ErrorTable extends AbstractTableFieldBeanData {

    private static final long serialVersionUID = 1L;

    @Override
    public ErrorTableRowData addRow() {
      return (ErrorTableRowData) super.addRow();
    }

    @Override
    public ErrorTableRowData addRow(int rowState) {
      return (ErrorTableRowData) super.addRow(rowState);
    }

    @Override
    public ErrorTableRowData createRow() {
      return new ErrorTableRowData();
    }

    @Override
    public Class<? extends AbstractTableRowData> getRowType() {
      return ErrorTableRowData.class;
    }

    @Override
    public ErrorTableRowData[] getRows() {
      return (ErrorTableRowData[]) super.getRows();
    }

    @Override
    public ErrorTableRowData rowAt(int index) {
      return (ErrorTableRowData) super.rowAt(index);
    }

    public void setRows(ErrorTableRowData[] rows) {
      super.setRows(rows);
    }

    public static class ErrorTableRowData extends AbstractTableRowData {

      private static final long serialVersionUID = 1L;
      public static final String severity = "severity";
      public static final String text = "text";
      private String m_severity;
      private String m_text;

      public String getSeverity() {
        return m_severity;
      }

      public void setSeverity(String newSeverity) {
        m_severity = newSeverity;
      }

      public String getText() {
        return m_text;
      }

      public void setText(String newText) {
        m_text = newText;
      }
    }
  }
}
