package ch.ahoegger.docbox.shared.document;

import java.math.BigDecimal;
import java.util.Date;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "ch.ahoegger.docbox.client.document.DocumentSearchForm", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class DocumentSearchFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  public Abstract getAbstract() {
    return getFieldByClass(Abstract.class);
  }

  public ActiveBox getActiveBox() {
    return getFieldByClass(ActiveBox.class);
  }

  public Conversation getConversation() {
    return getFieldByClass(Conversation.class);
  }

  public DocumentDateFrom getDocumentDateFrom() {
    return getFieldByClass(DocumentDateFrom.class);
  }

  public DocumentDateTo getDocumentDateTo() {
    return getFieldByClass(DocumentDateTo.class);
  }

  public Owner getOwner() {
    return getFieldByClass(Owner.class);
  }

  public Partner getPartner() {
    return getFieldByClass(Partner.class);
  }

  public static class Abstract extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class ActiveBox extends AbstractValueFieldData<DocumentActiveState> {

    private static final long serialVersionUID = 1L;
  }

  public static class Conversation extends AbstractValueFieldData<BigDecimal> {

    private static final long serialVersionUID = 1L;
  }

  public static class DocumentDateFrom extends AbstractValueFieldData<Date> {

    private static final long serialVersionUID = 1L;
  }

  public static class DocumentDateTo extends AbstractValueFieldData<Date> {

    private static final long serialVersionUID = 1L;
  }

  public static class Owner extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class Partner extends AbstractValueFieldData<BigDecimal> {

    private static final long serialVersionUID = 1L;
  }
}
