package ch.ahoegger.docbox.shared.document;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.basic.table.AbstractTableRowData;
import org.eclipse.scout.rt.shared.data.page.AbstractTablePageData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "ch.ahoegger.docbox.client.document.DocumentTablePage", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class DocumentTableData extends AbstractTablePageData {

  private static final long serialVersionUID = 1L;

  @Override
  public DocumentTableRowData addRow() {
    return (DocumentTableRowData) super.addRow();
  }

  @Override
  public DocumentTableRowData addRow(int rowState) {
    return (DocumentTableRowData) super.addRow(rowState);
  }

  @Override
  public DocumentTableRowData createRow() {
    return new DocumentTableRowData();
  }

  @Override
  public Class<? extends AbstractTableRowData> getRowType() {
    return DocumentTableRowData.class;
  }

  @Override
  public DocumentTableRowData[] getRows() {
    return (DocumentTableRowData[]) super.getRows();
  }

  @Override
  public DocumentTableRowData rowAt(int index) {
    return (DocumentTableRowData) super.rowAt(index);
  }

  public void setRows(DocumentTableRowData[] rows) {
    super.setRows(rows);
  }

  public static class DocumentTableRowData extends AbstractTableRowData {

    private static final long serialVersionUID = 1L;
    public static final String documentId = "documentId";
    public static final String abstract_ = "abstract";
    public static final String partner = "partner";
    public static final String documentPath = "documentPath";
    private Long m_documentId;
    private String m_abstract;
    private String m_partner;
    private String m_documentPath;

    public Long getDocumentId() {
      return m_documentId;
    }

    public void setDocumentId(Long newDocumentId) {
      m_documentId = newDocumentId;
    }

    public String getAbstract() {
      return m_abstract;
    }

    public void setAbstract(String newAbstract) {
      m_abstract = newAbstract;
    }

    public String getPartner() {
      return m_partner;
    }

    public void setPartner(String newPartner) {
      m_partner = newPartner;
    }

    public String getDocumentPath() {
      return m_documentPath;
    }

    public void setDocumentPath(String newDocumentPath) {
      m_documentPath = newDocumentPath;
    }
  }
}
