package ch.ahoegger.docbox.shared.document;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.eclipse.scout.rt.platform.resource.BinaryResource;
import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "ch.ahoegger.docbox.client.document.DocumentForm", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class DocumentFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  public Abstract getAbstract() {
    return getFieldByClass(Abstract.class);
  }

  public Document getDocument() {
    return getFieldByClass(Document.class);
  }

  public Partner getPartner() {
    return getFieldByClass(Partner.class);
  }

  public static class Abstract extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class Document extends AbstractValueFieldData<BinaryResource> {

    private static final long serialVersionUID = 1L;
  }

  public static class Partner extends AbstractValueFieldData<BigDecimal> {

    private static final long serialVersionUID = 1L;
  }
}
