package ch.ahoegger.docbox.shared.administration.user;

import java.math.BigDecimal;
import java.util.Set;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "ch.ahoegger.docbox.client.administration.user.UserForm", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class UserFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  public Active getActive() {
    return getFieldByClass(Active.class);
  }

  public Firstname getFirstname() {
    return getFieldByClass(Firstname.class);
  }

  public Name getName() {
    return getFieldByClass(Name.class);
  }

  public Password getPassword() {
    return getFieldByClass(Password.class);
  }

  public RoleBox getRoleBox() {
    return getFieldByClass(RoleBox.class);
  }

  public Username getUsername() {
    return getFieldByClass(Username.class);
  }

  public static class Active extends AbstractValueFieldData<Boolean> {

    private static final long serialVersionUID = 1L;
  }

  public static class Firstname extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class Name extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class Password extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }

  public static class RoleBox extends AbstractValueFieldData<Set<BigDecimal>> {

    private static final long serialVersionUID = 1L;
  }

  public static class Username extends AbstractValueFieldData<String> {

    private static final long serialVersionUID = 1L;
  }
}
