package ch.ahoegger.docbox.shared.administration.user;

import javax.annotation.Generated;

import org.eclipse.scout.rt.shared.data.basic.table.AbstractTableRowData;
import org.eclipse.scout.rt.shared.data.page.AbstractTablePageData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "ch.ahoegger.docbox.client.administration.user.UserTablePage", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class UserTablePageData extends AbstractTablePageData {

  private static final long serialVersionUID = 1L;

  @Override
  public UserTableRowData addRow() {
    return (UserTableRowData) super.addRow();
  }

  @Override
  public UserTableRowData addRow(int rowState) {
    return (UserTableRowData) super.addRow(rowState);
  }

  @Override
  public UserTableRowData createRow() {
    return new UserTableRowData();
  }

  @Override
  public Class<? extends AbstractTableRowData> getRowType() {
    return UserTableRowData.class;
  }

  @Override
  public UserTableRowData[] getRows() {
    return (UserTableRowData[]) super.getRows();
  }

  @Override
  public UserTableRowData rowAt(int index) {
    return (UserTableRowData) super.rowAt(index);
  }

  public void setRows(UserTableRowData[] rows) {
    super.setRows(rows);
  }

  public static class UserTableRowData extends AbstractTableRowData {

    private static final long serialVersionUID = 1L;
    public static final String username = "username";
    public static final String name = "name";
    public static final String firstname = "firstname";
    private String m_username;
    private String m_name;
    private String m_firstname;

    public String getUsername() {
      return m_username;
    }

    public void setUsername(String newUsername) {
      m_username = newUsername;
    }

    public String getName() {
      return m_name;
    }

    public void setName(String newName) {
      m_name = newName;
    }

    public String getFirstname() {
      return m_firstname;
    }

    public void setFirstname(String newFirstname) {
      m_firstname = newFirstname;
    }
  }
}
