DROP TABLE PRIMARY_KEY_SEQ;
DROP TABLE DOCUMENT;
DROP TABLE CATEGORY;
DROP TABLE DOCUMENT_CATEGORY;
DROP TABLE COMPANY;

CREATE TABLE PRIMARY_KEY_SEQ (LAST_VAL BIGINT);

CREATE TABLE DOCUMENT (
  DOCUMENT_NR DECIMAL NOT NULL,
  ABSTRACT VARCHAR(3000) NOT NULL,
  COMPANY_NR DECIMAL,
  DOCUMENT_DATE DATE NOT NULL,
  INSERT_DATE DATE NOT NULL,
  VALID_DATE DATE,
  DOCUMENT_URL VARCHAR(1200),
  ORIGINAL_STORAGE VARCHAR(1200),
  PAYMENT_DATE DATE,
  PRIMARY KEY (DOCUMENT_NR)
);

CREATE TABLE CATEGORY (
  CATEGORY_NR DECIMAL NOT NULL,
  TEXT VARCHAR(240) NOT NULL,
  DESCRIPTION VARCHAR(2000),
  START_DATE DATE ,
  END_DATE DATE ,
  PRIMARY KEY (CATEGORY_NR)
);

CREATE TABLE DOCUMENT_CATEGORY (
  DOCUMENT_NR DECIMAL NOT NULL,
  CATEGORY_NR DECIMAL NOT NULL,
  PRIMARY KEY (DOCUMENT_NR,CATEGORY_NR)
);

CREATE TABLE COMPANY (
  COMPANY_NR DECIMAL NOT NULL,
  NAME VARCHAR(480) NOT NULL,
  DESCRIPTION VARCHAR(2000),
  START_DATE DATE ,
  END_DATE DATE ,
  PRIMARY KEY (COMPANY_NR)
);


INSERT INTO CATEGORY (CATEGORY_NR, TEXT, START_DATE) VALUES (1,'Versicherung', DATE('2010-01-01'));
INSERT INTO CATEGORY (CATEGORY_NR, TEXT, START_DATE) VALUES (2,'Rechnungen', DATE('2010-01-01'));
INSERT INTO CATEGORY (CATEGORY_NR, TEXT, START_DATE) VALUES (3,'Lohn/Salär', DATE('2010-01-01'));
INSERT INTO CATEGORY (CATEGORY_NR, TEXT, START_DATE) VALUES (4,'Wohnen', DATE('2010-01-01'));
INSERT INTO CATEGORY (CATEGORY_NR, TEXT, START_DATE) VALUES (5,'Finanzen', DATE('2010-01-01'));
INSERT INTO CATEGORY (CATEGORY_NR, TEXT, START_DATE) VALUES (6,'Unterhaltung', DATE('2010-01-01'));
INSERT INTO CATEGORY (CATEGORY_NR, TEXT, START_DATE) VALUES (7,'Sport', DATE('2010-01-01'));
INSERT INTO CATEGORY (CATEGORY_NR, TEXT, START_DATE) VALUES (8,'Gesundheit', DATE('2010-01-01'));
INSERT INTO CATEGORY (CATEGORY_NR, TEXT, START_DATE) VALUES (9,'Fahrzeuge', DATE('2010-01-01'));



INSERT INTO COMPANY (COMPANY_NR, NAME, DESCRIPTION, START_DATE) VALUES (10,'Open Source', NULL , DATE('2010-01-01'));
--INSERT INTO COMPANY (COMPANY_NR, NAME, DESCRIPTION, START_DATE) VALUES (11,'Hypothekarbank Lenzburg (HBL)', NULL , DATE('2010-01-01'));
--INSERT INTO COMPANY (COMPANY_NR, NAME, DESCRIPTION, START_DATE) VALUES (12,'Cablecom', NULL , DATE('2010-01-01'));
--INSERT INTO COMPANY (COMPANY_NR, NAME, DESCRIPTION, START_DATE) VALUES (13,'Stadt Baden', NULL , DATE('2010-01-01'));
--INSERT INTO COMPANY (COMPANY_NR, NAME, DESCRIPTION, START_DATE) VALUES (14,'Staat Schweiz', NULL , DATE('2010-01-01'));
--INSERT INTO COMPANY (COMPANY_NR, NAME, DESCRIPTION, START_DATE) VALUES (15,'Dössegger Garage Seon', NULL , DATE('2010-01-01'));
--INSERT INTO COMPANY (COMPANY_NR, NAME, DESCRIPTION, START_DATE) VALUES (16,'Turing Club Schweiz (TCS)', NULL , DATE('2010-01-01'));
--INSERT INTO COMPANY (COMPANY_NR, NAME, DESCRIPTION, START_DATE) VALUES (17,'Zahnartzzentrum Baden', NULL , DATE('2010-01-01'));
--INSERT INTO COMPANY (COMPANY_NR, NAME, DESCRIPTION, START_DATE) VALUES (18,'Allianz Suisse', NULL , DATE('2010-01-01'));
--INSERT INTO COMPANY (COMPANY_NR, NAME, DESCRIPTION, START_DATE) VALUES (19,'Spinout Hendschiken', NULL , DATE('2010-01-01'));

INSERT INTO PRIMARY_KEY_SEQ (LAST_VAL) VALUES (20);