-- EXAMPLE: ALTER TABLE APP.EMPLOYEE ADD NEW_COL VARCHAR(25);

RENAME TABLE POSTING_GROUP TO PAYSLIP_ACCOUNTING;
RENAME COLUMN PAYSLIP_ACCOUNTING.POSTING_GROUP_NR TO PAYSLIP_ACCOUNTING_NR; 
RENAME COLUMN ENTITY.POSTING_GROUP_NR TO PAYSLIP_ACCOUNTING_NR;

CREATE TABLE EMPLOYEE_TAX_GROUP (PARTNER_NR BIGING NOT NULL, TAX_GROUP_NR BIGINT NOT NULL, DOCUMENT_NR BIGINT, PRIMARY KEY (PARTNER_NR, TAX_GROUP_NR));

Select * from PAYSLIP_ACCOUNTING