package ch.ahoegger.docbox.shared.hr.tax;

import java.math.BigDecimal;

import javax.annotation.Generated;

import org.eclipse.scout.rt.platform.classid.ClassId;
import org.eclipse.scout.rt.shared.data.form.AbstractFormData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;
import org.eclipse.scout.rt.shared.data.form.properties.AbstractPropertyData;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "ch.ahoegger.docbox.client.hr.tax.EmployeeTaxGroupForm", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public class EmployeeTaxGroupFormData extends AbstractFormData {

  private static final long serialVersionUID = 1L;

  /**
   * access method for property PartnerId.
   */
  public BigDecimal getPartnerId() {
    return getPartnerIdProperty().getValue();
  }

  /**
   * access method for property PartnerId.
   */
  public void setPartnerId(BigDecimal partnerId) {
    getPartnerIdProperty().setValue(partnerId);
  }

  public PartnerIdProperty getPartnerIdProperty() {
    return getPropertyByClass(PartnerIdProperty.class);
  }

  public TaxGroup getTaxGroup() {
    return getFieldByClass(TaxGroup.class);
  }

  public static class PartnerIdProperty extends AbstractPropertyData<BigDecimal> {

    private static final long serialVersionUID = 1L;
  }

  @ClassId("deb10e43-62be-4f54-90c4-e664f76bb111-formdata")
  public static class TaxGroup extends AbstractValueFieldData<BigDecimal> {

    private static final long serialVersionUID = 1L;
  }
}
